language: node_js

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y libax25 ax25-apps ax25-tools libax25-dev
 
node_js:
  - 12

cache:
  directories:
  - node_modules
  - ".nvm"
